version: '3'
services:
  app:
    build: .
    image: melyo/docker-node-init:1.0
    env_file: ./docker.env
    command: sh /home/app/init.sh
    ports:
      - '5000:5000'
    volumes:
      - .:/home/app
